"""empty message

Revision ID: 050cfb9fe750
Revises: eacc1682ab0f
Create Date: 2022-03-07 19:08:48.290309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050cfb9fe750'
down_revision = 'eacc1682ab0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_orders', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
