"""empty message

Revision ID: 3b47b4438202
Revises: a019082e6477
Create Date: 2022-03-16 23:51:55.442633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b47b4438202'
down_revision = 'a019082e6477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
