"""empty message

Revision ID: a320ac2e75d9
Revises: b191a7dc8eb8
Create Date: 2022-03-16 23:24:30.989652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a320ac2e75d9'
down_revision = 'b191a7dc8eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
