"""empty message

Revision ID: be5bb03d3650
Revises: 07a1c9d2c247
Create Date: 2022-03-07 18:59:24.511854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be5bb03d3650'
down_revision = '07a1c9d2c247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_orders', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
